### ISSUE TITLE
The tool seems to strugle when converting some custom 64 bit behaviours

### ISSUE THREAD

**Issue by NickaNak** [ret2end/HKX2Library#1]
When trying to run a conversion on some custom made 64 bit behaviours it seems to have trouble processing them, it creates an error and just fails, there's quite a few behaviours I'm trying to convert and only one file gets converted, I haven't checked in the behaviour editor if it's working or not though

Also why is it trying to find a non existent user in the C Drive?
`C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\`
That's not my user name and I don't  have the tool nor havok content tools/hkxcmd in my C drive

Here's the full error log:
```
Unhandled exception: System.InvalidCastException: Unable to cast object of type 'HKX2.hkbStateMachineStateInfo' to type 'HKX2.hkbExpressionDataArray'.
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkbEvaluateExpressionModifier.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbEvaluateExpressionModifier.cs:line 22
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkbModifierGenerator.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbModifierGenerator.cs:line 19
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkbStateMachineStateInfo.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbStateMachineStateInfo.cs:line 38
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.PackFileDeserializer.<>c__DisplayClass14_0`1.<ReadArrayBase>b__0(BinaryReaderEx _br, LocalFixup f) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 145
   at HKX2.PackFileDeserializer.ReadPointerBase[T,F](Func`3 func, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 130
   at HKX2.hkbStateMachine.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbStateMachine.cs:line 88
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkbModifierGenerator.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbModifierGenerator.cs:line 20
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkbStateMachineStateInfo.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbStateMachineStateInfo.cs:line 38
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.PackFileDeserializer.<>c__DisplayClass14_0`1.<ReadArrayBase>b__0(BinaryReaderEx _br, LocalFixup f) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 145
   at HKX2.PackFileDeserializer.ReadPointerBase[T,F](Func`3 func, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 130
   at HKX2.hkbStateMachine.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbStateMachine.cs:line 88
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkbBehaviorGraph.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Autogen\hkbBehaviorGraph.cs:line 82
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at HKX2.PackFileDeserializer.ReadClassPointer[T](BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 176
   at HKX2.hkRootLevelContainerNamedVariant.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Manual\hkRootLevelContainerNamedVariant.cs:line 26
   at HKX2.PackFileDeserializer.<ReadClassArray>b__15_0[T](BinaryReaderEx _br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 158
   at HKX2.PackFileDeserializer.<>c__DisplayClass14_0`1.<ReadArrayBase>b__0(BinaryReaderEx _br, LocalFixup f) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 145
   at HKX2.PackFileDeserializer.ReadPointerBase[T,F](Func`3 func, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 130
   at HKX2.hkRootLevelContainer.Read(PackFileDeserializer des, BinaryReaderEx br) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\Manual\hkRootLevelContainer.cs:line 20
   at HKX2.PackFileDeserializer.ConstructVirtualClass(BinaryReaderEx br, UInt32 offset, Type sourceType) in C:\Users\yee\source\repos\hkxconv\HKX2Library\HKX2\PackFileDeserializer.cs:line 39
   at hkxconv.cmd.Convert.ConvertHKX(FileInfo inFile, FileInfo outFile, ConvertFormat format, Boolean verbose) in C:\Users\yee\source\repos\hkxconv\hkxconv\cmd\Convert.cs:line 88
   at hkxconv.cmd.Convert.ConvertHKX(DirectoryInfo inDir, DirectoryInfo outDir, ConvertFormat format, Boolean verbose) in C:\Users\yee\source\repos\hkxconv\hkxconv\cmd\Convert.cs:line 49
   at hkxconv.cmd.Convert.ToFormat(FileSystemInfo input, FileSystemInfo output, ConvertFormat format, Boolean verbose) in C:\Users\yee\source\repos\hkxconv\hkxconv\cmd\Convert.cs:line 30
   at hkxconv.Program.<>c.<Main>b__0_3(ConvertFormat format, Boolean verbose, FileSystemInfo input, FileSystemInfo output) in C:\Users\yee\source\repos\hkxconv\hkxconv\Program.cs:line 31
   at System.CommandLine.Handler.<>c__DisplayClass5_0`4.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by ret2end** [comment]
lol that my pc username and project path. i guess next time not to bundle with pdb

also some modifed hkx by GenerateFNISforModders.exe (probably older version?)
have same error
could reproduce same error here
https://github.com/ret2end/HKX2Library/issues/5

thinking a way to ignore error or skip deserialize

look like hkx try put `hkbStateMachineStateInfo` class in  `expressions` member which is `hkbExpressionDataArray` class
https://github.com/ret2end/HKX2Library/blob/8451526f7eb62baee9c82466dbedc2f109344423/HKX2/Autogen/hkbEvaluateExpressionModifier.cs#L13

**Comment by NickaNak** [comment]
Thanks for the quick reply! I've been told by the author of these behaviours, that these have trouble with Nemesis too, he was having trouble turning them into Nemesis compatible behaviours(so that users could mod them if they wanted to) so it's something the author has done, not your tool

Just tested your tool on the VR behaviours and they work great!

**Comment by ret2end** [comment]
I release hkxconv v0.1.1-alpha
with `--ignore-cast-error` flag should ignore all error above (if hkx file not so mess up lol).
but output will missing some data (data still in original file)
error above `hkbStateMachineStateInfo` will be missing in xml and child reference etc.
preserve skipped class will on todo list (still thinking how to handle).

nice to hear VR work too. it shoud be able convert any havok 2010.2.0-r1 hkx file.
btw i don't own skyrim VR, not sure there is any VR specific hk class.
